### ISSUE TITLE
nsenter deprecated

### ISSUE THREAD

**Issue by petiepooo** [mrschyte/dockerpot#1]
Since docker v1.3, nsenter is no longer needed, as the "exec" verb is officially supported by the CLI. https://docs.docker.com/reference/commandline/cli/#exec

I'd suggest rewriting your scripts to use exec, and forego the need to install nsenter.

**Comment by mrschyte** [comment]
Thank you for your suggestion, but nsenter is used for entering the network namespace, so "docker exec" wont work here. I could rewrite the script to use "ip netns exec", but it would require me to symlink the docker network namespaces to /var/run/netns, which is a bit messy in my opinion.
